spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/weather_db}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:weatheruser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:weatherpass}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.application.name=weather
server.port=${SERVER_PORT:8084}
